name: Springfield Ben Franklin Crafts
favicon: null
layout_spectrum: 0.42464841855689883
typography_spectrum: 0.07830799254588783
title: 'Ben Franklin Crafts | Springfield'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d52323'
    - '#020101'
    - '#eb9797'
    - '#606060'
  brandStrength: 1
  lightness: 0.6629226573277265
  saturation: 0.962546847993508
  rhythmicContrast: 0.2949523392599076
purpose: []
