name: Springfield Ben Franklin Crafts
favicon: null
layout_spectrum: 0.42464841855689883
typography_spectrum: 0.07830799254588783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8574587306939065
  lightness: 0.6629226573277265
  saturation: 0.962546847993508
  rhythmicContrast: 0.2949523392599076
purpose: []
